name: Testing pipeline
on:[push]
jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - name : checkout repository code
        uses : actions/checkout@v3
      - uses : actions/setup-python@v2
        with:
          python-version : 3.8
      -name : install repository
      run : |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt;
        python -m pytest .